import Foundation

/// Converts a Markdown first-line title into a safe, stable filename base.
enum TitleFilename {
    static let maximumUTF8Bytes = 120

    static func sanitizedBaseName(_ title: String) -> String? {
        let characters = title.unicodeScalars.map { scalar -> Character in
            switch scalar {
            case "/", ":": return "-"
            default: return Character(String(scalar))
            }
        }
        .filter { character in
            !character.unicodeScalars.contains {
                CharacterSet.controlCharacters.contains($0)
            }
        }
        var value = String(characters)

        // The scalar pass above intentionally keeps the original graphemes
        // out of the path-building logic. Re-collapse whitespace on the
        // resulting string so tabs and runs of spaces become one separator.
        value = value
            .split(whereSeparator: { $0.isWhitespace })
            .joined(separator: " ")

        while value.first == "." { value.removeFirst() }
        while value.last == "." || value.last == " " { value.removeLast() }

        guard !value.isEmpty, value != ".", value != ".." else { return nil }

        var truncated = ""
        for character in value {
            guard (truncated + String(character)).utf8.count <= maximumUTF8Bytes else {
                break
            }
            truncated.append(character)
        }
        while truncated.last == "." || truncated.last == " " { truncated.removeLast() }
        guard !truncated.isEmpty, truncated != ".", truncated != ".." else { return nil }
        return truncated
    }

    /// Collision suffixes generated by `LibraryBrowser.availableURL` do not
    /// retrigger title renaming: `Groceries 2.md` already represents title
    /// `Groceries` after the first collision.
    static func matches(_ fileName: String, title: String) -> Bool {
        guard let desired = sanitizedBaseName(title) else { return false }
        let currentBase = (fileName as NSString).deletingPathExtension
        guard currentBase == desired else {
            let prefix = desired + " "
            guard currentBase.hasPrefix(prefix) else { return false }
            let suffix = String(currentBase.dropFirst(prefix.count))
            guard let number = Int(suffix) else { return false }
            return number >= 2
        }
        return true
    }
}
